### ISSUE TITLE
Please Make This Usable In Windows, Please?

### ISSUE THREAD

**Issue by Dro2000** [witheve/Eve#333]
Using Cygwin in Windows to try go through the steps to install.  On attempt 30 or so I think.
Relatively new to the frameworks and packages used in its development, so this is causing headaches.

Finally found out how to get node running with Windows+Cygwin, then tried the run.sh, which tells me to run ./install-multirust.sh

First attempt:
Submodule path 'test/multirust-v1': checked out '2eaf9067314307320d27be510e1ac3949a21eee9'
blastoff: installing
./install-multirust.sh: line 121: sudo: command not found
blastoff: failed to install multirust

Alright fine, open the script and get rid of all the sudo and try again:

Submodule path 'test/multirust-v1': checked out '2eaf9067314307320d27be510e1ac3949a21eee9'
blastoff: installing
install: uninstalling component 'multirust'
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'multirust'
build/work/multirust-0.7.0/install.sh: line 384: uname_value: unbound variable
blastoff: failed to install multirust

Bah!

I like the readme instructions:
Eve relies on TypeScript, Rust Nightly, and multirust. You'll want these installed, though our run.sh will attempt to install them for you.

bash run.sh

we're working on a nice experience for windows, but we suggest trying to use cygwin and doing the above for now

I am using cygwin and doing the above (probably wrong) and getting nowhere.

The last run.sh attempt:
$ ./run.sh
* Installing commit hooks...done.
* Checking dependencies...module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\home\User\Projects\Eve\ui\node_modules\typescript\bin\tsc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

  x Eve requires tsc version "1.6.2" but "" is installed. Please reinstall using:
    cd ui && npm install && cd .. before continuing.

Can you add Cygwin instructions for all of us (or maybe just me?) that can't piece together the install?  I can't see what I am missing here.

**Comment by cmontella** [comment]
Don't worry, it's not just you; when we released Eve Version 0, Rust support on Windows was very tenuous, and we honestly didn't test on Windows at all. Today Rust support for Windows is much better, but the Version 0 graph editor is still stuck at Rust 1.3. If you'd like to try, you can upgrade to Rust 1.5 and try to resolve any issues that comes along with that. In fact, you might not need to use Cygwin at all, as rust 1.5 links against native windows libraries (I don't know how far you'll get with the packages though). Then you can use node natively in windows to compile the UI.

One thing I'd like to point out is that multirust isn't a hard dependency; it was just a convenient way to switch between Rust versions.

Ultimately, our work on the graph editor released with Version 0 has concluded; We're focusing our development on experimental\cardwiki, which you'll be happy to know as of yesterday has a build script that works in Windows! Give it a try and let us know how it works out. We'll be coming out with more docs and better instructions for the next release, so sit tight!

**Comment by vprimachenko** [comment]
@Dro2000 in case you want to check the development on `experimental\cardwiki` here's my hacky way to get it running

1. download zip
2. extract only the `experimental\cardwiki` folder
3. edit `run.sh`
    
    ```diff
--- D:\Desktop\wikidata\cardwiki\run.sh	Thu Jan 14 11:09:12 2016
+++ D:\Desktop\wikidata\cardwiki\run.sh	Thu Jan 14 21:32:26 2016
@@ -88,1 +88,1 @@
-node_modules/tsify/node_modules/typescript/bin/tsc --watch -m commonjs 2>&1 | tag "typescript" "$blue" &
+node_modules/.bin/tsc --watch -m commonjs 2>&1 | tag "typescript" "$blue" &
```
4. `bash run.sh` from `cmd` or maybe just `./run.sh` on cygwin (i use MSYS2)
5. after it bundle's `runtimeTest` kill it
6. move content from `bin/src/` to `bin/`
7. `node bin/server.js`

**Comment by joshuafcole** [comment]
Our new node-based run script just landed, which adds experimental support
for windows. Can you try running
`node run.js -v --width 80` and then visit the editor at
`<path\to\eve>\experimental\cardwiki.editor.html` and confirm if it works
for you? Bundling may take a while, so keep an eye on the status indicators
and wait til they turn green. You don't need the server to be running
(that's another experiment for multi-user, which isn't quite ready for
primetime, though should still work).

Cheers,
Josh

**Comment by vprimachenko** [comment]
the instruction i posted were intended to be used with last properly working ui version (or pref d26af08a via [Eve talk](https://groups.google.com/forum/#!topic/eve-talk/b4_RikU1vVc)), which was before `run.js` landed. Should have wrote that i guess :)

as to `run.js`
i need to install `livereload` manually even after `npm i`
also i need to create the `bin` folder myself
then the script succeeds and i can use the `editor.html`

**Comment by Dro2000** [comment]
Thanks for the information!  I still cannot get this to work due to my inexperience with Linux and the frameworks used.  I have a windows box and a remote linux box connection and have tried a few times in both messing around but there are always errors or missing packages or something doesn't install or work correctly.

I am sure I could get it working if I was super dedicated on a mission to try this out but as it is still beta and full of warnings to not use it for anything production so I am not that dedicated..... yet.

I will be watching this project closely though and very much look forward to a "click-and-run" demo when/if it becomes available.

So far from the few bits I have seen this looks like an excellent concept, I just hope it comes to be at some point.

As a tongue in cheek side rant prompted by this experience:

I hear Windows getting bashed all the time since it is not as "cool" as Linux but I find I can focus on the work I want to do.  As soon as you hit Linux you need to become a IT/OS/framework/programming/package/vim/vi/bash/script/makefile/etc/etc professional to even just get something to run.  I have tested many a Windows demo (and C/C++/C# git clone VS projects) with typically nothing more than a double-click or a build button but wow this Linux stuff is crazy.  I know I can be faulted for resisting Linux (as it is the flavor of the decade now) but I do not have as much interest in becoming a command-line OS and package configuration god as I do with actually using software to accomplish something.  From my brief time so far in Linux I find you spend ALOT of time becoming the former rather then achieving the latter.

Although I can understand the whole Linux thing since you feel like you are in a movie/tv show as a main super cool hacker character when a bunch of confused people are standing around watching them type furiously as messages in text scroll up the screen.  (pffft gui!? who needs that crap anyways)  And it does seem to impress people somewhat when you, as a super-"hacker"-hero, facing a blank black window with nothing but a bash prompt, can AT WILL summon the powers that be to do your bidding.  And its great because just like a good actor you can find some good commands with a healthy amount of scrolling text to really drive home the "this is just like a movie/tv show" effect.  (Or break out VIM and do some editing in a source file mid-stream, unbelievable!)  I am guessing this is part of the attraction to Linux.  Windows is so boring with things just mostly working out of the box, with intuitive visual menus and buttons.  (I know I know, there are exceptions and I have had to go through some painful troubleshooting but at least you could click-search your way to a solution, a blank flashing prompt requires intimate knowledge of the internal workings to even start to figure anything out)

It reminds me of when I was looking at a bunch of LISP code and thought it was a ridiculous language due to horrible readability to people not familiar with it, I was told that its probably because LISP coders enjoy the puzzle of the language itself, not just the puzzle of coding a good solution to accomplish something.  Seems similar to Linux, people must enjoy the puzzle of the OS itself and its not enough to just run an application, you really need a challenge there to feel acceptably accomplished.  (Nothing is as good as when you have to really work hard for it, then it becomes much more satisfying on a psychological level)

And you can really draw this out to a more general level.  You can become like one of those telephone psychics and really surprise people.  You notice someone going to fill up with gas at a pump but they back into the pump stall with the gas cap facing the wrong side so they have to drag and weave the hose in a complex way to avoid scratching the paint!?  You are pretty safe to assume that once approaching them and they say they program for a living that they are probably involved with Linux and a language similar to LISP.  They crave a challenge for the task at hand, no matter how mundane.

And vice versa, if someone works with Linux and you have to do a real-world task strap yourself in because you are not taking the easy direct way to achieve it.

**Comment by vprimachenko** [comment]
i went so far and packaged two runnable versions of Eve for you @Dro2000 

recent (a3690de9 based) version [here](https://dl.dropboxusercontent.com/u/14672987/Eve-a3690de9.zip)
and older (67a0d14e based) version [here](https://dl.dropboxusercontent.com/u/14672987/eve-67a0d14e.zip) which i prefer myself

sometimes Eve will fail to load, the only way i found to fix it is to clean the storage by running
```js
delete localStorage["local-eve"]
```
in browsers console
:exclamation: this will delete all the data you have saved in Eve

**Comment by Dro2000** [comment]
Wow thanks!  This is awesome!  Thank you for doing that, I have tried both versions @vprimachenko  has uploaded in Firefox and they do not render correctly.  There is a couple of boxes I can type text into but no save, and if I close that box there is nothing.  Only a few numbers about the version in the upper right hand corner of the page.

The newer version has a title bar with a magnifying glass search but does not do anything when I click on it.  I see #pet and Pet is test data but nothing else.

I am thinking I am really going to need to get a Linux box up or a VM going to try the install steps again.  It does not look like there is a way for me to get this working in Windows/Cygwin with my level of knowledge.

**Comment by Dro2000** [comment]
Alright I tried downloading and running again and get the following with the latest experimental card-wiki (in Cygwin):

$ ./run.sh
# Updating node_modules...
npm WARN package.json eve@0.0.0 No README data
# Symlinking vendor for node execution...
# Starting watchers...
17:16:17 [typescript] src/server.ts(4,27): error TS2307: Cannot find module 'compression'.
17:16:18 [typescript] 5:16:18 PM - Compilation complete. Watching for file changes.
17:16:18 [richTextEditorTest] TypeScript error: src/richTextEditor.ts(7,1): Error TS2304: Cannot find name 'require'.
17:16:18 [richTextEditorTest] TypeScript error: src/richTextEditor.ts(8,1): Error TS2304: Cannot find name 'require'.
17:16:18 [richTextEditorTest] TypeScript error: src/richTextEditor.ts(95,7): Error TS2345: Argument of type '{ mode: string; lineWrapping: boolean; autoCloseBrackets: boolean; viewportMargin: number; extraK...' is not assignable to parameter of type 'EditorConfiguration'.
17:16:18 [richTextEditorTest] Object literal may only specify known properties, and 'autoCloseBrackets' does not exist in type 'EditorConfiguration'.
17:16:18 [editor] TypeScript error: src/richTextEditor.ts(7,1): Error TS2304: Cannot find name 'require'.
17:16:18 [runtimeTest] TypeScript error: src/richTextEditor.ts(7,1): Error TS2304: Cannot find name 'require'.
17:16:18 [richTextEditorTest] TypeScript error: src/utils.ts(7,21): Error TS2304: Cannot find name 'exports'.
17:16:19 [runtimeTest] TypeScript error: src/richTextEditor.ts(8,1): Error TS2304: Cannot find name 'require'.
17:16:19 [editor] TypeScript error: src/richTextEditor.ts(8,1): Error TS2304: Cannot find name 'require'.
17:16:19 [runtimeTest] TypeScript error: src/richTextEditor.ts(95,7): Error TS2345: Argument of type '{ mode: string; lineWrapping: boolean; autoCloseBrackets: boolean; viewportMargin: number; extraK...' is not assignable to parameter of type 'EditorConfiguration'.
17:16:19 [editor] TypeScript error: src/richTextEditor.ts(95,7): Error TS2345: Argument of type '{ mode: string; lineWrapping: boolean; autoCloseBrackets: boolean; viewportMargin: number; extraK...' is not assignable to parameter of type 'EditorConfiguration'.
17:16:19 [queryParserTest] TypeScript error: src/richTextEditor.ts(7,1): Error TS2304: Cannot find name 'require'.
17:16:19 [runtimeTest] Object literal may only specify known properties, and 'autoCloseBrackets' does not exist in type 'EditorConfiguration'.
17:16:19 [queryParserTest] TypeScript error: src/richTextEditor.ts(8,1): Error TS2304: Cannot find name 'require'.
17:16:19 [runtimeTest] TypeScript error: src/utils.ts(7,21): Error TS2304: Cannot find name 'exports'.
17:16:19 [editor] Object literal may only specify known properties, and 'autoCloseBrackets' does not exist in type 'EditorConfiguration'.
17:16:19 [queryParserTest] TypeScript error: src/richTextEditor.ts(95,7): Error TS2345: Argument of type '{ mode: string; lineWrapping: boolean; autoCloseBrackets: boolean; viewportMargin: number; extraK...' is not assignable to parameter of type 'EditorConfiguration'.
17:16:19 [editor] TypeScript error: src/utils.ts(7,21): Error TS2304: Cannot find name 'exports'.
17:16:19 [queryParserTest] Object literal may only specify known properties, and 'autoCloseBrackets' does not exist in type 'EditorConfiguration'.
17:16:19 [queryParserTest] TypeScript error: src/utils.ts(7,21): Error TS2304: Cannot find name 'exports'.

**Comment by ibdknox** [comment]
try running `npm install` first

**Comment by ibdknox** [comment]
Ah looks like there was something else wrong that Corey just fixed. Try pulling and then run:

```
npm install
npm run dev
```
and then go to http://localhost:3000/

**Comment by Dro2000** [comment]
I get:
"KILLING PROCS" in the Cygwin terminal when I try this.  Moving the mouse around in the cygwin terminal causes random input to scroll across as well.  Always 3 characters at a time and the rate of input is proportional to the mouse movement.  Maybe this is a feature of some module, not sure.

"Unable to connect"
when navigating to the localhost:3000

There were a bunch of errors during the npm install, the number of lines appearing to be related to the errors was > 50 so will have to investigate later

This time when npm run dev the windows firewall exception request dialog popped up which is new and exiciting.  progress!

**Comment by cmontella** [comment]
Eve will work in Windows going forward. At the very least, we will have a Docker container, but I develop in Windows full time, so I am invested in making sure it works here.

**Comment by Dro2000** [comment]
I also request something that works in Windows.  Please make something that runs like software (from the installs I have tried it is a complex convoluted process and I have not been able to use the software as of yet….)

**Comment by cmontella** [comment]
Dro2000,

As a Windows user myself, I feel your pain. Do you use Docker at all? I myself have not until now, so I'm curious how Windows users perceive it. I've found that for the user side, the experience was pretty seamless on Windows.
